# -*- coding: utf-8 -*-
"""Wind_energy_dhaka_2017.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Hanifahmed/wind-energy-dhaka-2017/blob/main/notebooks/Wind_energy_dhaka_2017.ipynb
"""

# ================================
# 1. Install required package
# ================================

!pip install windrose -q

# ================================
# 2. Import libraries
# ================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pathlib import Path
from scipy.stats import weibull_min
from scipy.integrate import trapezoid
from scipy.special import gamma

from windrose import WindroseAxes

print("Libraries loaded successfully.")

# ================================
# 3. Mount Google Drive
# ================================

from google.colab import drive

drive.mount("/content/drive")

# ================================
# 4. Set data file
# ================================

CSV_FILE = Path(
    "/content/drive/MyDrive/WindProject/Dhaka_2017/data/nrel_dhaka_100m_2017.csv"
)

if CSV_FILE.exists():
    print("Data file found.")
    print(CSV_FILE)
else:
    print("Data file not found.")
    print("Please check the CSV_FILE path.")

# ================================
# 5. Load NREL data
# ================================

df = pd.read_csv(
    CSV_FILE,
    skiprows=1
)

print("Data shape:")
print(df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst five rows:")
display(df.head())

# ================================
# 6. Rename important variables
# ================================

df = df.rename(columns={
    "wind speed at 100m (m/s)": "wind_speed_100m",
    "wind direction at 100m (deg)": "wind_direction_100m",
    "air temperature at 100m (C)": "temperature_100m"
})

print("Important columns:")
print([
    "wind_speed_100m",
    "wind_direction_100m",
    "temperature_100m"
])

# ================================
# 7. Create datetime
# ================================

df["datetime"] = pd.to_datetime(
    df[["Year", "Month", "Day", "Hour", "Minute"]]
)

df = df.set_index("datetime")

df = df.sort_index()

print("Start:", df.index.min())
print("End:", df.index.max())

# ================================
# 8. Prepare analysis dataframe
# ================================

df_site = df[
    [
        "wind_speed_100m",
        "wind_direction_100m",
        "temperature_100m"
    ]
].copy()

# Make sure the variables are numerical
df_site["wind_speed_100m"] = pd.to_numeric(
    df_site["wind_speed_100m"],
    errors="coerce"
)

df_site["wind_direction_100m"] = pd.to_numeric(
    df_site["wind_direction_100m"],
    errors="coerce"
)

df_site["temperature_100m"] = pd.to_numeric(
    df_site["temperature_100m"],
    errors="coerce"
)

print("Analysis dataframe:")
display(df_site.head())

print("\nShape:")
print(df_site.shape)

# ================================
# 9. Basic quality control
# ================================

print("Number of observations:")
print(len(df_site))

print("\nMissing values:")
print(df_site.isna().sum())

print("\nBasic statistics:")
display(df_site.describe())

# ================================
# 10. Wind-speed quality check
# ================================

wind_speed = df_site["wind_speed_100m"]

print("Minimum wind speed:", wind_speed.min(), "m/s")
print("Maximum wind speed:", wind_speed.max(), "m/s")
print("Mean wind speed:", wind_speed.mean(), "m/s")

print("\nNumber of zero-wind observations:")
print((wind_speed == 0).sum())

# ================================
# 11. Check hourly coverage
# ================================

expected_hours = 8760
actual_hours = len(df_site)

print("Expected observations:", expected_hours)
print("Actual observations:", actual_hours)

if actual_hours == expected_hours:
    print("Complete hourly dataset for 2017.")
else:
    print("Some hourly observations are missing.")

# ================================
# 12. Wind-speed histogram
# ================================

plt.figure(figsize=(8, 5))

plt.hist(
    wind_speed.dropna(),
    bins=25,
    edgecolor="black"
)

plt.xlabel("Wind speed at 100 m (m/s)")
plt.ylabel("Number of observations")
plt.title("Wind Speed Distribution - Dhaka 2017")

plt.show()

# ================================
# 13. Monthly mean wind speed
# ================================

monthly_mean = (
    df_site["wind_speed_100m"]
    .resample("ME")
    .mean()
)

plt.figure(figsize=(9, 5))

plt.plot(
    monthly_mean.index,
    monthly_mean.values,
    marker="o"
)

plt.xlabel("Month")
plt.ylabel("Mean wind speed (m/s)")
plt.title("Monthly Mean Wind Speed at 100 m")

plt.grid(alpha=0.3)

plt.show()

# ================================
# 14. Monthly wind statistics
# ================================

monthly_statistics = (
    df_site["wind_speed_100m"]
    .resample("ME")
    .agg(["mean", "min", "max"])
)

monthly_statistics.index = monthly_statistics.index.month

monthly_statistics.index.name = "Month"

display(monthly_statistics)

# ================================
# 15. Diurnal wind-speed variation
# ================================

hourly_mean = (
    df_site["wind_speed_100m"]
    .groupby(df_site.index.hour)
    .mean()
)

plt.figure(figsize=(9, 5))

plt.plot(
    hourly_mean.index,
    hourly_mean.values,
    marker="o"
)

plt.xlabel("Hour of day")
plt.ylabel("Mean wind speed (m/s)")
plt.title("Diurnal Variation of Wind Speed")

plt.xticks(range(0, 24))

plt.grid(alpha=0.3)

plt.show()

import matplotlib.pyplot as plt
from windrose import WindroseAxes

# ================================
# 16. Wind rose
# ================================

wind_direction = df_site["wind_direction_100m"]
wind_speed_clean = df_site["wind_speed_100m"]

valid = (
    wind_direction.notna()
    & wind_speed_clean.notna()
)

ax = WindroseAxes.from_ax()

ax.bar(
    wind_direction[valid],
    wind_speed_clean[valid],
    opening=0.8,
    edgecolor="white",
    bins=[0, 1, 3, 5, 7, 9, 12]
)

ax.set_title("Wind Rose - Dhaka 2017")

ax.set_legend()

plt.show()

# ================================
# 17. Weibull distribution
# ================================

wind_data = wind_speed.dropna().values

# Fit Weibull distribution
shape, location, scale = weibull_min.fit(
    wind_data,
    floc=0
)

k = shape
c = scale

print(f"Weibull shape parameter (k): {k:.2f}")
print(f"Weibull scale parameter (c): {c:.2f} m/s")

# ================================
# 18. Weibull fit
# ================================

x = np.linspace(
    0,
    wind_data.max(),
    200
)

weibull_pdf = weibull_min.pdf(
    x,
    k,
    loc=0,
    scale=c
)

plt.figure(figsize=(8, 5))

plt.hist(
    wind_data,
    bins=25,
    density=True,
    alpha=0.5,
    label="Observed wind speed"
)

plt.plot(
    x,
    weibull_pdf,
    linewidth=2,
    label="Weibull distribution"
)

plt.xlabel("Wind speed (m/s)")
plt.ylabel("Probability density")

plt.title("Weibull Fit of 100 m Wind Speed")

plt.legend()

plt.show()

# ================================
# 19. Wind Power Density
# ================================

rho = 1.225  # kg/m³

# Mean of V^3 from Weibull distribution
mean_v3 = (
    c**3
    * gamma(1 + 3 / k)
)

WPD = 0.5 * rho * mean_v3

print(f"Mean cubic wind speed: {mean_v3:.2f} m³/s³")
print(f"Wind Power Density: {WPD:.1f} W/m²")

# ================================
# 20. Simple turbine power curve
# ================================

def turbine_power_curve(
    wind_speed,
    rated_power=2000,
    cut_in=3,
    rated_speed=12,
    cut_out=25
):

    power = np.zeros_like(wind_speed)

    # Between cut-in and rated speed
    rising = (
        (wind_speed >= cut_in)
        & (wind_speed < rated_speed)
    )

    power[rising] = (
        rated_power
        * (
            (wind_speed[rising] - cut_in)
            / (rated_speed - cut_in)
        ) ** 3
    )

    # Rated power region
    rated = (
        (wind_speed >= rated_speed)
        & (wind_speed <= cut_out)
    )

    power[rated] = rated_power

    return power

# ================================
# 21. Plot turbine power curve
# ================================

wind_range = np.linspace(0, 30, 500)

power_curve = turbine_power_curve(
    wind_range
)

plt.figure(figsize=(8, 5))

plt.plot(
    wind_range,
    power_curve
)

plt.xlabel("Wind speed (m/s)")
plt.ylabel("Power output (kW)")
plt.title("Simplified 2 MW Turbine Power Curve")

plt.grid(alpha=0.3)

plt.show()

# ================================
# 22. Expected mean turbine power
# ================================

pdf = weibull_min.pdf(
    wind_range,
    k,
    loc=0,
    scale=c
)

expected_power = trapezoid(
    power_curve * pdf,
    wind_range
)

print(
    f"Expected mean power: {expected_power:.1f} kW"
)

# ================================
# 23. Annual Energy Production
# ================================

rated_power = 2000  # kW
hours_per_year = 8760

AEP = expected_power * hours_per_year

capacity_factor = (
    expected_power / rated_power
)

print(
    f"Annual Energy Production: "
    f"{AEP / 1000:.1f} MWh/year"
)

print(
    f"Capacity Factor: "
    f"{capacity_factor * 100:.1f}%"
)

# ================================
# 24. Hub-height sensitivity
# ================================

reference_height = 100
alpha = 0.14

hub_heights = [50, 80, 100, 120]

results = []

for height in hub_heights:

    scale_factor = (
        height / reference_height
    ) ** alpha

    adjusted_scale = c * scale_factor

    pdf = weibull_min.pdf(
        wind_range,
        k,
        loc=0,
        scale=adjusted_scale
    )

    power_curve = turbine_power_curve(
        wind_range,
        rated_power=2000
    )

    mean_power = trapezoid(
        power_curve * pdf,
        wind_range
    )

    AEP = (
        mean_power
        * hours_per_year
        / 1000
    )

    CF = mean_power / rated_power

    results.append({
        "Hub height (m)": height,
        "Mean wind speed (m/s)": (
            adjusted_scale
            * gamma(1 + 1 / k)
        ),
        "Mean power (kW)": mean_power,
        "AEP (MWh/year)": AEP,
        "Capacity factor (%)": CF * 100
    })

results_df = pd.DataFrame(results)

display(results_df.round(2))

# ================================
# 25. Project summary
# ================================

print("================================")
print(" WIND ENERGY ANALYSIS SUMMARY")
print("================================")

print(f"Location: Dhaka, Bangladesh")
print(f"Year: 2017")
print(f"Wind-data height: 100 m")

print(f"\nNumber of observations: {len(df_site)}")

print(
    f"Mean wind speed: "
    f"{wind_speed.mean():.2f} m/s"
)

print(
    f"Weibull k: {k:.2f}"
)

print(
    f"Weibull c: {c:.2f} m/s"
)

print(
    f"Wind Power Density: "
    f"{WPD:.1f} W/m²"
)

print(
    f"2 MW turbine mean power: "
    f"{expected_power:.1f} kW"
)

print(
    f"Estimated AEP: "
    f"{AEP:.1f} MWh/year"
)

print(
    f"Estimated capacity factor: "
    f"{capacity_factor * 100:.1f}%"
)

# ================================
# 26. Save cleaned data
# ================================

cleaned_file = (
    CSV_FILE.parent
    / "dhaka_2017_cleaned.csv"
)

df_site.to_csv(cleaned_file)

print("Cleaned dataset saved:")
print(cleaned_file)